/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.coltin.bored

class Library {

    companion object {

        @JvmStatic
        fun main(args: Array<String>) {
            println("DEV DOT TO")
        }
    }

    fun someLibraryMethod(): Boolean {
        return true
    }
}
