/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.coltin.bored

import com.coltin.bored.mbti.Mbti.INTJ

class Main {

    companion object {

        @JvmStatic
        fun main(args: Array<String>) {
            println(INTJ.egoFunctions())
            println(INTJ.unconciousFunctions())
            println(INTJ.subconciousFunctions())
            println(INTJ.superegoFunctions())
        }
    }

}
