/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.coltin.bored

import com.coltin.bored.mbti.Functions
import com.coltin.bored.mbti.Functions.Ni
import com.coltin.bored.mbti.Mbti
import com.coltin.bored.mbti.Mbti.INTJ

class Main {

    companion object {

        @JvmStatic
        fun main(args: Array<String>) {
            println(INTJ.functions())
            println(INTJ.nemesis())
            println(INTJ.critic())
            println(INTJ.trickster())
            println(INTJ.demon())
        }
    }

}
